"""create exploration_session

Revision ID: 0d44c4377400
Revises: 8cafe7161b60
Create Date: 2026-07-27 21:18:15.319638

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d44c4377400'
down_revision: Union[str, Sequence[str], None] = '8cafe7161b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploration_session',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_exploration_session_user_id_project_id')
    )
    op.create_index(op.f('ix_exploration_session_project_id'), 'exploration_session', ['project_id'], unique=False)
    op.create_index(op.f('ix_exploration_session_user_id'), 'exploration_session', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exploration_session_user_id'), table_name='exploration_session')
    op.drop_index(op.f('ix_exploration_session_project_id'), table_name='exploration_session')
    op.drop_table('exploration_session')
    # ### end Alembic commands ###
