"""extend exploration_message and create story_clue

Revision ID: 687df87a3cb1
Revises: ea0c8c0bb98d
Create Date: 2026-07-28 21:42:33.216917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687df87a3cb1'
down_revision: Union[str, Sequence[str], None] = 'ea0c8c0bb98d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_clue',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('clue_key', sa.String(length=32), nullable=True),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), server_default='', nullable=False),
    sa.Column('user_edited', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exploration_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'clue_key', name='uq_story_clue_session_id_clue_key')
    )
    op.create_index(op.f('ix_story_clue_project_id'), 'story_clue', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_clue_session_id'), 'story_clue', ['session_id'], unique=False)
    op.create_index(op.f('ix_story_clue_user_id'), 'story_clue', ['user_id'], unique=False)
    op.add_column('exploration_message', sa.Column('kind', sa.String(length=16), server_default='guided', nullable=False))
    op.add_column('exploration_message', sa.Column('role', sa.String(length=16), nullable=True))
    op.add_column('exploration_message', sa.Column('content', sa.Text(), nullable=True))
    op.alter_column('exploration_message', 'question_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exploration_message', 'question',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('exploration_message', 'answer',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('exploration_message', 'answer_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    先清理 free 行再收紧 NOT NULL：本迁移把 question_index/question/answer/answer_type 松绑为
    可空以容纳 free 对话行（这四列恒 NULL）。downgrade 直接 SET NOT NULL 会撞这些 NULL 值抛
    「column contains null values」而失败——故先物理删除全部 kind='free' 行（回退到只有 guided
    形态的旧 schema，free 对话数据在旧 schema 下本就无处安放，删除是回退的固有语义）。
    story_clue 整表 drop 同理不保留。**此操作有数据损失，仅用于开发/回滚场景**。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM exploration_message WHERE kind = 'free'")
    op.alter_column('exploration_message', 'answer_type',
               existing_type=sa.VARCHAR(length=16),
               nullable=False)
    op.alter_column('exploration_message', 'answer',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('exploration_message', 'question',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('exploration_message', 'question_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exploration_message', 'content')
    op.drop_column('exploration_message', 'role')
    op.drop_column('exploration_message', 'kind')
    op.drop_index(op.f('ix_story_clue_user_id'), table_name='story_clue')
    op.drop_index(op.f('ix_story_clue_session_id'), table_name='story_clue')
    op.drop_index(op.f('ix_story_clue_project_id'), table_name='story_clue')
    op.drop_table('story_clue')
    # ### end Alembic commands ###
