"""add exploration_session guidance_state

Revision ID: 69fdf3588c3c
Revises: d29ada3ce1b3
Create Date: 2026-08-03 09:27:06.972750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69fdf3588c3c'
down_revision: Union[str, Sequence[str], None] = 'd29ada3ce1b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    ALTER 既有 exploration_session 表加 1 列（非建表，Story 2.8）。nullable=True、无
    server_default——本列只服务 free 模式：guided 会话与本迁移执行前既有的 free 会话
    均回填 NULL（历史 free 会话不主动回填初始态，由 enter_exploration 幂等编排读到
    None 时按需初始化；guidance_agent 各函数读到 None 时视为「未初始化」防御性兜底）。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exploration_session', sa.Column('guidance_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    纯删列的逆操作：删 guidance_state 列，其余表结构不动。删列有数据损失（导航状态丢弃），
    仅用于开发/回滚场景。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exploration_session', 'guidance_state')
    # ### end Alembic commands ###
