"""add story_bible status revision changed_fields

Revision ID: d29ada3ce1b3
Revises: ffa52c6a4e27
Create Date: 2026-07-29 20:39:46.170103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd29ada3ce1b3'
down_revision: Union[str, Sequence[str], None] = 'ffa52c6a4e27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    ALTER 既有 story_bible 表加 3 列（非建表，Story 3.4）。server_default 保证既有行回填不为 NULL。
    status 默认 'draft'：迁移执行时既有行都是「只锚了文风、还没跑 settle 凝练」的半成品行
    （3.4 之前从无候选卡落库），标 draft 而非 pending——避免被 get_pending_by_project 误当候选卡
    返回（code review 2026-07-29 发现 1）。settle 落库时才显式写 status='pending'。changed_fields 可空。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_bible', sa.Column('status', sa.Text(), server_default='draft', nullable=False))
    op.add_column('story_bible', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('story_bible', sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    纯加列的逆操作：反序删 3 列（changed_fields/revision/status），12 内容字段与约束不动。
    删列有数据损失（status/revision/changed_fields 值丢弃），仅用于开发/回滚场景。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_bible', 'changed_fields')
    op.drop_column('story_bible', 'revision')
    op.drop_column('story_bible', 'status')
    # ### end Alembic commands ###
