"""create chapter_generation_run

Revision ID: e5e0b47fef12
Revises: 69fdf3588c3c
Create Date: 2026-08-04 15:57:18.627405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e5e0b47fef12'
down_revision: Union[str, Sequence[str], None] = '69fdf3588c3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_generation_run',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), server_default='running', nullable=False),
    sa.Column('steps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chapter_idea', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'chapter_number', name='uq_chapter_generation_run_user_project_chapter')
    )
    op.create_index(op.f('ix_chapter_generation_run_project_id'), 'chapter_generation_run', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapter_generation_run_user_id'), 'chapter_generation_run', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    纯新增表，无 alter：直接删索引 + 删表即可，无数据清理特例（chapter_generation_run
    整表随之丢弃，本操作有数据损失，仅用于开发/回滚场景）。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chapter_generation_run_user_id'), table_name='chapter_generation_run')
    op.drop_index(op.f('ix_chapter_generation_run_project_id'), table_name='chapter_generation_run')
    op.drop_table('chapter_generation_run')
    # ### end Alembic commands ###
