"""create exploration_message

Revision ID: ea0c8c0bb98d
Revises: 0d44c4377400
Create Date: 2026-07-28 14:32:10.076783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea0c8c0bb98d'
down_revision: Union[str, Sequence[str], None] = '0d44c4377400'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exploration_message',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('question_index', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exploration_session.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_index', name='uq_exploration_message_session_id_question_index')
    )
    op.create_index(op.f('ix_exploration_message_project_id'), 'exploration_message', ['project_id'], unique=False)
    op.create_index(op.f('ix_exploration_message_session_id'), 'exploration_message', ['session_id'], unique=False)
    op.create_index(op.f('ix_exploration_message_user_id'), 'exploration_message', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exploration_message_user_id'), table_name='exploration_message')
    op.drop_index(op.f('ix_exploration_message_session_id'), table_name='exploration_message')
    op.drop_index(op.f('ix_exploration_message_project_id'), table_name='exploration_message')
    op.drop_table('exploration_message')
    # ### end Alembic commands ###
