"""create chapter_card story_thread story_state

Revision ID: f472170cd859
Revises: 55130c002b17
Create Date: 2026-08-06 10:17:44.704576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f472170cd859'
down_revision: Union[str, Sequence[str], None] = '55130c002b17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Story 5.1：一次迁移建三张归档域业务表（chapter_card / story_state / story_thread），
    每张都是「FK user + FK project + 复合唯一（chapter_card / story_state 有，
    story_thread 故意无）+ 2 列级索引」——三表同属 Epic 5 一致性核心表，同一迁移
    事务天然原子（避免分三次迁移的中间态窗口）。`down_revision = '55130c002b17'`
    （Story 4.4 章正文表 head，4.5/4.6/4.7 均为零迁移）。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter_card',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('what_happened', sa.Text(), server_default='', nullable=False),
    sa.Column('character_changes', sa.Text(), server_default='', nullable=False),
    sa.Column('new_facts_clues', sa.Text(), server_default='', nullable=False),
    sa.Column('unresolved_hooks', sa.Text(), server_default='', nullable=False),
    sa.Column('end_state', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', 'chapter_number', name='uq_chapter_card_user_project_chapter')
    )
    op.create_index(op.f('ix_chapter_card_project_id'), 'chapter_card', ['project_id'], unique=False)
    op.create_index(op.f('ix_chapter_card_user_id'), 'chapter_card', ['user_id'], unique=False)
    op.create_table('story_state',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('protagonist_state', sa.Text(), server_default='', nullable=False),
    sa.Column('world_rules_state', sa.Text(), server_default='', nullable=False),
    sa.Column('current_stage', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_story_state_user_id_project_id')
    )
    op.create_index(op.f('ix_story_state_project_id'), 'story_state', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_state_user_id'), 'story_state', ['user_id'], unique=False)
    op.create_table('story_thread',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('status', sa.Text(), server_default='open', nullable=False),
    sa.Column('introduced_chapter_number', sa.Integer(), nullable=False),
    sa.Column('resolved_chapter_number', sa.Integer(), nullable=True),
    sa.Column('last_touched_chapter_number', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_thread_project_id'), 'story_thread', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_thread_user_id'), 'story_thread', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    纯新增表，无 alter：反序删索引+删表即可，无数据清理特例（三张归档表随之丢弃，
    本操作有数据损失，仅用于开发/回滚场景——与 story_bible/chapter 等所有建表迁移
    既有先例一致）。story_thread 先删（无外键依赖）、再 story_state、再 chapter_card，
    顺序与 upgrade 反向（实际三表互相无 FK 交叉，任何顺序都安全，但保持 backwards
    一致性便于 review）。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_thread_user_id'), table_name='story_thread')
    op.drop_index(op.f('ix_story_thread_project_id'), table_name='story_thread')
    op.drop_table('story_thread')
    op.drop_index(op.f('ix_story_state_user_id'), table_name='story_state')
    op.drop_index(op.f('ix_story_state_project_id'), table_name='story_state')
    op.drop_table('story_state')
    op.drop_index(op.f('ix_chapter_card_user_id'), table_name='chapter_card')
    op.drop_index(op.f('ix_chapter_card_project_id'), table_name='chapter_card')
    op.drop_table('chapter_card')
    # ### end Alembic commands ###
