"""create story_bible

Revision ID: ffa52c6a4e27
Revises: 687df87a3cb1
Create Date: 2026-07-29 16:09:43.084737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffa52c6a4e27'
down_revision: Union[str, Sequence[str], None] = '687df87a3cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_bible',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('genre', sa.Text(), server_default='', nullable=False),
    sa.Column('core_appeal', sa.Text(), server_default='', nullable=False),
    sa.Column('protagonist', sa.Text(), server_default='', nullable=False),
    sa.Column('main_conflict', sa.Text(), server_default='', nullable=False),
    sa.Column('world_rules', sa.Text(), server_default='', nullable=False),
    sa.Column('overall_tone', sa.Text(), server_default='', nullable=False),
    sa.Column('opening_hook', sa.Text(), server_default='', nullable=False),
    sa.Column('power_system', sa.Text(), nullable=True),
    sa.Column('golden_finger', sa.Text(), nullable=True),
    sa.Column('romance_line', sa.Text(), nullable=True),
    sa.Column('faction_landscape', sa.Text(), nullable=True),
    sa.Column('style_profile', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_story_bible_user_id_project_id')
    )
    op.create_index(op.f('ix_story_bible_project_id'), 'story_bible', ['project_id'], unique=False)
    op.create_index(op.f('ix_story_bible_user_id'), 'story_bible', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    纯新增表，无 alter：直接删索引 + 删表即可，无数据清理特例（story_bible 整表随之丢弃，
    本操作有数据损失，仅用于开发/回滚场景）。
    """
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_bible_user_id'), table_name='story_bible')
    op.drop_index(op.f('ix_story_bible_project_id'), table_name='story_bible')
    op.drop_table('story_bible')
    # ### end Alembic commands ###
